- name: Git clone Openstack-Ansible
  git:
      repo: https://opendev.org/openstack/openstack-ansible
      dest: /opt/openstack-ansible/
      version: master

- name: Bootstrap Ansible
  shell: "./scripts/bootstrap-ansible.sh"
  args:
    chdir: /opt/openstack-ansible

- name: Copy /etc/openstack_deploy folder
  shell: "cp -r /opt/openstack-ansible/etc/openstack_deploy /etc/openstack_deploy"

- name: Copy user_config to /etc/openstack_deploy/
  shell: "cp {{ user_config_path }} /etc/openstack_deploy/openstack_user_config.yml"

- name: Copy user_variables to /etc/openstack_deploy/
  shell: "cp {{ user_variables_path }} /etc/openstack_deploy/user_variables.yml"

- name: Generate user_secrets.yml
  shell: "./scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml"
  args:
    chdir: /opt/openstack-ansible
