---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###
### This file contains commonly used overrides for convenience. Please inspect
### the defaults for each role to find additional override options.
###

## Debug and Verbose options.
debug: true
swift_allow_all_users: True
horizon_enable_password_retrieve: True
horizon_images_upload_mode: legacy
magnum_config_overrides:
  cinder:
    default_docker_volume_type: lvm
horizon_custom_uploads:
  logo:
    src: "/etc/openstack_deploy/logo.svg"
    dest: "img/logo.svg"
  logo_splash:
    src: "/etc/openstack_deploy/logo-splash.svg"
    dest: "img/logo-splash.svg"
_horizon_available_themes:
  default:
    theme_name: "default"
    theme_label: "Default"
    theme_path: "themes/default"
  material:
    theme_name: "material"
    theme_label: "Material"
    theme_path: "themes/material"
  bcp_theme:
    theme_name: "bcp_theme"
    theme_label: "BCP Theme"
    theme_path: "themes/bcp_theme"
horizon_custom_themes:
  bcp_theme:
    theme_name: "bcp_theme"
    theme_label: "BCP Theme"
    theme_path: "themes/bcp_theme"
    theme_src_archive: "/etc/openstack_deploy/horizon/themes/bcp_theme.tar.gz"
horizon_default_theme: "bcp_theme"

# octavia
octavia_service_net_setup: False
octavia_neutron_management_network_name: external_net
octavia_provider_network_name: physnet1
octavia_ssh_enabled: True
