---
###
### This file contains commonly used overrides for convenience. Please inspect
### the defaults for each role to find additional override options.
###

debug: True
swift_allow_all_users: True
horizon_enable_password_retrieve: True
horizon_images_upload_mode: legacy
magnum_config_overrides:
  cinder:
    default_docker_volume_type: lvm
haproxy_ssl_letsencrypt_certbot_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
haproxy_ssl: true
haproxy_ssl_letsencrypt_enable: True
haproxy_ssl_letsencrypt_install_method: "distro"
haproxy_ssl_letsencrypt_email: "admin@oulhafiane.me"
