- name: Get a backup of old config
  shell: "cp /etc/network/interfaces /root/old_interfaces"

- name: Delete old config for interface will be used for creating vlans
  shell: "head -n -7 /etc/network/interfaces > /tmp/tmp.txt && mv /tmp/tmp.txt /etc/network/interfaces"

- name: Add interfaces.d folder to interfaces
  shell: "echo 'source /etc/network/interfaces.d/*.cfg' >> /etc/network/interfaces"

- name: Configure networks
  template:
    src: openstack_interface.j2
    dest: /etc/network/interfaces.d/openstack_interface.cfg 
  vars:
      ip: "{{ hostvars[inventory_hostname]['ansible_facts'][ext_interface_name]['ipv4']['address'] }}"

- name: Reboot machines
  reboot:
  when: 'inventory_hostname != "localhost"'
