- name: Configure Network For OpenStack
  hosts: AllNodes
  user: vagrant
  roles:
      - { role: "configure_network", ext_interface_name: "eth1", interface_name: "eth2", tags: ['configure-network'] }
  become: yes
