- name: Install Galera server
  hosts: ControllerNode
  user: vagrant
  roles:
    - galera_server
  vars:
    galera_install_server: true
    galera_install_client: true
    galera_cluster_members: "{{ groups['ControllerNode'] }}"
    galera_root_password: secrete
  become: yes
- name: Install Memcached
  hosts: memcached
  user: vagrant
  roles:
    - { role: "memcached_server" }
