- name: Assign nodes to appropriate groups
  hosts: localhost
  tasks:
    - name : Assign ControllerNodes to appropriate groups
      add_host:
        name: '{{ item }}'
        groups:
          - galera_all
          - haproxy
          - memcached
          - rabbitmq_all
          - horizon_all
          - keystone_all
          - neutron_all
          - neutron_ovn_northd
          - placement_all
      with_items: "{{ groups['ControllerNode'] }}"
    - name : Assign ComputeNodes to appropriate groups
      add_host:
        name: '{{ item }}'
        groups:
          - rabbitmq_all
          - memcached
          - nova_all
          - nova_api_metadata
          - nova_api_os_compute
          - nova_cert
          - nova_compute
          - nova_conductor
          - nova_console
          - nova_scheduler
          - glance_all
          - cinder_all
          - cinder_volume
      with_items: "{{ groups['ComputeNode'] }}"
- name: Gather all facts
  hosts: all
  gather_facts: true
- name: Install Memcached
  hosts: memcached
  user: vagrant
  roles:
    - { role: "memcached_server" }
  become: yes
- name: Install Galera server
  hosts: galera_all
  user: vagrant
  roles:
    - galera_server
  vars:
    galera_install_server: true
    galera_install_client: true
    galera_cluster_members: "{{ groups['ControllerNode'] }}"
    galera_root_password: secrete
  become: yes
- name: Install RabbitMQ server
  hosts: rabbitmq_all
  user: vagrant
  tags:
    - rabbitmq
  roles:
    - { role: "rabbitmq_server", tags: [ "rabbitmq-server" ] }
  vars:
    rabbitmq_host_group: all
    rabbitmq_cookie_token: secrete
  become: yes
- name: Create OpenStack openrc and clouds.yaml file
  hosts: localhost
  user: vagrant
  roles:
    - role: "openstack_openrc"
  vars:
    openrc_os_auth_url: "http://{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}:5000"
    openrc_os_password: secrete
  become: yes
- name: Installation and setup of Keystone
  hosts: keystone_all
  user: vagrant
  roles:
    - { role: "os_keystone", tags: [ "os-keystone" ] }
  vars:
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"

    external_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_galera_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_facts']['eth0']['ipv4']['address'] }}" 
    keystone_galera_database: keystone
    keystone_developer_mode: true
    keystone_git_install_branch: master
    keystone_auth_admin_password: "secrete"
    keystone_oslomsg_rpc_password: "secrete"
    keystone_oslomsg_notify_password: "secrete"
    keystone_container_mysql_password: "secrete"
    keystone_oslomsg_rpc_transport: rabbit
    keystone_oslomsg_rpc_servers: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_oslomsg_rpc_port: 5671
    keystone_oslomsg_rpc_use_ssl: true
    keystone_oslomsg_rpc_userid: keystone
    keystone_oslomsg_rpc_vhost: /keystone
    keystone_oslomsg_notify_transport: rabbit
    keystone_oslomsg_notify_servers: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_oslomsg_notify_port: 5671
    keystone_oslomsg_notify_use_ssl: true
    keystone_oslomsg_notify_userid: keystone
    keystone_oslomsg_notify_vhost: /keystone
    galera_client_drop_config_file: false
    galera_root_user: root
    galera_root_password: secrete
    keystone_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_oslomsg_rpc_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_oslomsg_notify_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    memcached_servers: "127.0.0.1:11211"
    oslomsg_rpc_policies: 
      - name: "HA"
        pattern: '^(?!(amq\.)|(.*_fanout_)|(reply_)).*'
        priority: 0
        tags: "ha-mode=all"
  become: yes
- name: Install placement components
  hosts: placement_all
  user: vagrant
  roles:
    - role: os_placement
  vars:
    memcached_servers: "127.0.0.1:11211"
    keystone_service_adminuri: "http://{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}:5000"
    keystone_service_adminurl: "{{ keystone_service_adminuri }}/v3"
    keystone_service_internaluri: "{{ keystone_service_adminuri }}"
    keystone_service_internalurl: "{{ keystone_service_adminurl }}"
    keystone_service_publicuri: "{{ keystone_service_adminuri }}"
    keystone_service_publicurl: "{{ keystone_service_adminurl }}"
    placement_service_password: "secrete"
    keystone_service_region: "RegionOne"
    memcached_encryption_key: "secrete"
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_facts']['eth0']['ipv4']['address'] }}"
    external_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    placement_galera_address: "{{ internal_lb_vip_address }}"
    placement_galera_password: "secrete"
    placement_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_service_internaluri_insecure: False
    keystone_service_adminuri_insecure: False
  become: yes
- name: Install glance server
  hosts: glance_all
  user: vagrant
  roles:
    - { role: "os_glance", tags: [ "os-glance" ] }
  vars:
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"

    external_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    glance_galera_address: "{{ internal_lb_vip_address }}"
    galera_root_user: root
    galera_root_password: root
    glance_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    glance_oslomsg_rpc_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    glance_oslomsg_notify_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    memcached_servers: "127.0.0.1:11211"
    oslomsg_rpc_policies: 
      - name: "HA"
        pattern: '^(?!(amq\.)|(.*_fanout_)|(reply_)).*'
        priority: 0
        tags: "ha-mode=all"
    keystone_service_internaluri_insecure: False
    glance_oslomsg_rpc_password: "secrete"
    glance_container_mysql_password: "secrete"
    keystone_service_adminuri: "http://{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}:5000"
    keystone_service_adminurl: "{{ keystone_service_adminuri }}/v3"
    keystone_service_internaluri: "{{ keystone_service_adminuri }}"
    keystone_service_internalurl: "{{ keystone_service_adminurl }}"
    glance_service_password: "secrete"
    keystone_service_region: "RegionOne"
    memcached_encryption_key: "secrete"
  become: yes
- name: Installation and setup of cinder
  hosts: cinder_all
  user: vagrant
  roles:
    - { role: "os_cinder", tags: [ "os-cinder" ] }
  vars:
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    cinder_glance_api_servers: "http://{{ hostvars[groups['glance_all'][0]]['ansible_facts']['eth0']['ipv4']['address'] }}:9292"
    cinder_galera_address: "{{ internal_lb_vip_address }}"
    galera_root_user: root
    galera_root_password: "secreet"
    cinder_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    cinder_oslomsg_rpc_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    cinder_oslomsg_notify_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    memcached_servers: "127.0.0.1:11211"
    debug: False
    oslomsg_rpc_policies: 
      - name: "HA"
        pattern: '^(?!(amq\.)|(.*_fanout_)|(reply_)).*'
        priority: 0
        tags: "ha-mode=all"
    cinder_container_mysql_password: "secrete"
    cinder_oslomsg_rpc_password: "secrete"
    cinder_profiler_hmac_key: "secrete"
    keystone_service_internaluri_insecure: False
    keystone_service_adminuri: "http://{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}:5000"
    keystone_service_adminurl: "{{ keystone_service_adminuri }}/v3"
    keystone_service_internaluri: "{{ keystone_service_adminuri }}"
    keystone_service_internalurl: "{{ keystone_service_adminurl }}"
    cinder_service_password: "secrete"
    keystone_service_region: "RegionOne"
    memcached_encryption_key: "secrete"
  become: yes
- name: Add root@hostname user to gallera
  hosts: ControllerNode
  user: vagrant
  tasks:
    - name: adding galera user
      community.mysql.mysql_user:
        name: "root"
        host: "{{ groups['ControllerNode'][0] }}"
        password: "secrete"
        priv: "*.*:ALL,GRANT"
        state: "present"
  become: yes
- name: Installation and setup of Nova
  hosts: nova_all
  user: vagrant
  roles:
    - { role: "os_nova", tags: [ "os-nova" ] }
  vars:
    nova_galera_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    galera_root_user: root
    galera_root_password: secrete
    nova_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    nova_oslomsg_rpc_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    nova_container_mysql_password: secrete
    nova_api_container_mysql_password: secrete
    nova_oslomsg_rpc_password: secrete
    oslomsg_rpc_policies:
      - name: "HA"
        pattern: '^(?!(amq\.)|(.*_fanout_)|(reply_)).*'
        priority: 0
        tags: "ha-mode=all"
    oslomsg_notify_policies: "{{ oslomsg_rpc_policies }}"
    nova_libvirtd_listen_tls: 0
    nova_qemu_vnc_tls: 0
    memcached_servers: "127.0.0.1:11211"
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    external_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    keystone_service_internaluri_insecure: False
    nova_service_password: "secrete"
    keystone_service_adminuri: "http://{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}:5000"
    keystone_service_adminurl: "{{ keystone_service_adminuri }}/v3"
    keystone_service_internaluri: "{{ keystone_service_adminuri }}"
    keystone_service_internalurl: "{{ keystone_service_adminurl }}"
    keystone_service_adminuri_insecure: False
    nova_metadata_proxy_secret: "secrete"
    keystone_service_region: "RegionOne"
    memcached_encryption_key: "secrete"
  become: yes
- name: Installation and setup of Neutron
  hosts: neutron_all
  user: vagrant
  roles:
    - { role: "os_neutron", tags: [ "neutron-install", "neutron-config" ] }
  vars:
    neutron_galera_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_facts']['eth0']['ipv4']['address'] }}"
    galera_root_user: root
    galera_root_password: root
    neutron_db_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    neutron_oslomsg_rpc_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    neutron_oslomsg_notify_setup_host: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    neutron_oslomsg_rpc_password: "secrete"
    memcached_servers: "127.0.0.1:11211"
    oslomsg_rpc_policies: 
      - name: "HA"
        pattern: '^(?!(amq\.)|(.*_fanout_)|(reply_)).*'
        priority: 0
        tags: "ha-mode=all"
    provider_networks: "[]"
    is_metal: false
  become: yes
- name: Installation and setup of horizon
  hosts: horizon_all
  user: vagrant
  roles:
    - { role: "os_horizon", tags: [ "os-horizon" ] }
  vars:
    galera_client_drop_config_file: false
    external_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    internal_lb_vip_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    horizon_galera_address: "{{ hostvars[groups['ControllerNode'][0]]['ansible_host'] }}"
    horizon_container_mysql_password: "secrete"
    horizon_secret_key: "secrete"
    horizon_external_ssl: false
    rabbitmq_servers: rabbitmq_all
    rabbitmq_use_ssl: false
    rabbitmq_port: 5671
    keystone_admin_user_name: admin
    keystone_auth_admin_password: "secrete"
    keystone_admin_tenant_name: admin
    keystone_service_adminuri_insecure: false
    keystone_service_internaluri_insecure: false
    keystone_service_internaluri: "http://{{ internal_lb_vip_address }}:5000"
    keystone_service_internalurl: "{{ keystone_service_internaluri }}/v3"
    keystone_service_adminuri: "http://{{ internal_lb_vip_address }}:5000"
    keystone_service_adminurl: "{{ keystone_service_adminuri }}/v3"
    openrc_os_password: "{{ keystone_auth_admin_password }}"
    openrc_os_domain_name: "Default"
    memcached_servers: "127.0.0.1:11211"
    memcached_encryption_key: "secrete"
    galera_root_user: root
    galera_root_password: secrete
  become: yes
