- name: Install Galera server
  hosts: ControllerNode
  user: vagrant
  roles:
    - galera_server
  vars:
    galera_install_server: true
    galera_install_client: true
    galera_cluster_members: "{{ groups['ControllerNode'] }}"
    galera_root_password: secrete
  become: yes
- name: Install haproxy
  hosts: ControllerNode
  user: vagrant
  roles:
    - { role: "haproxy_server", tags: [ "haproxy-server" ] }
  vars:
    haproxy_service_configs:
      - service:
          haproxy_service_name: group_name
          haproxy_backend_nodes: "{{ groups['group_name'][0] }}"
          haproxy_backup_nodes: "{{ groups['group_name'][1:] }}"
          haproxy_port: 80
          haproxy_balance_type: http
          haproxy_backend_options:
            - "forwardfor"
            - "httpchk"
            - "httplog"
          haproxy_backend_arguments:
            - 'http-check expect string OK'
  become: yes
