- name: Install Galera server
  hosts: ControllerNode
  user: vagrant
  roles:
    - galera_server
  vars:
    galera_install_server: true
    galera_install_client: true
    galera_root_password: secrete
  become: yes
