- name: systemd_service
  src: https://opendev.org/openstack/ansible-role-systemd_service
  scm: git
  version: master
  trackbranch: master
- name: apt_package_pinning
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-apt_package_pinning
  version: master
  trackbranch: master
- name: galera_server
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-galera_server
  version: master
  trackbranch: master
- name: memcached_server
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-memcached_server
- name: pki
  src: https://opendev.org/openstack/ansible-role-pki
  scm: git
  version: master
  trackbranch: master
- name: haproxy_server
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-haproxy_server
  version: master
  trackbranch: master
- name: rabbitmq_server
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-rabbitmq_server
  version: master
  trackbranch: master
- name: openstack_openrc
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-openstack_openrc
  version: master
  trackbranch: master
- name: uwsgi
  src: https://opendev.org/openstack/ansible-role-uwsgi
  scm: git
  version: master
  trackbranch: master
- name: python_venv_build
  src: https://opendev.org/openstack/ansible-role-python_venv_build
  scm: git
  version: master
  trackbranch: master
- name: os_keystone
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-os_keystone
  version: master
  trackbranch: master
- name: os_nova
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-os_nova
  version: master
- name: ceph_client
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-ceph_client
  version: master
